#!/bin/bash

# Extract first 7 characters of last commit's sha
get_sha() {
    git rev-parse --short HEAD 2> /dev/null
}

# Find and source prompt enhancer shipped with git
enable_git_prompt(){
    if [ -f ~/.git-prompt.sh ]; then
        source ~/.git-prompt.sh
    fi
}

# Configure colors and other git properies for prompt
# This is called every time before PS1 gets evaluated
setup_prompt() {
    local CYAN="\[\033[0;36m\]"
    local LIGHT_GRAY="\[\033[0;37m\]"
    local GREEN="\[\033[0;32m\]"
    local MAGENTA="\[\033[0;35m\]"
    local YELLOW="\[\033[0;33m\]"
    local NO_COLOR="\[\033[0m\]"

    # unstaged (*) and staged (+)
    GIT_PS1_SHOWDIRTYSTATE=true
    # something is stashed ($)
    GIT_PS1_SHOWSTASHSTATE=true
    # untracked (%)
    GIT_PS1_SHOWUNTRACKEDFILES=true
    # behind (<), ahead (>), diverged (<>), same (=)
    GIT_PS1_SHOWUPSTREAM="auto verbose"

    if type -t __git_ps1 | grep -q "function"; then
        GIT_PROMPT="$(__git_ps1 "$MAGENTA(%s)")"
    fi

    PS1="$CYAN\u$LIGHT_GRAY@$GREEN\h$GIT_PROMPT $LIGHT_GRAY\w$YELLOW\$$NO_COLOR "
}

enable_git_prompt
PROMPT_COMMAND=setup_prompt
