tap "homebrew/cask"
tap "homebrew/cask-versions"
brew "make", args: ["force-bottle"]
brew "curl", args: ["force-bottle"]
brew "stow",
brew "git", args: ["force-bottle"]
brew "ghi"
brew "gist"
brew "tig"
brew "htop"
brew "tmux"
brew "tree"
brew "bash-completion" unless system "test -z $(which bash)"
brew "bash-git-prompt" unless system "test -z $(which bash)"
brew "brew-cask-completion" unless system "test -z $(which bash)"
brew "neovim"
brew "keychain"
cask "corretto"
cask "google-chrome" unless system "test -d '/Applications/Google Chrome.app'"
cask "spectacle" unless system "test -d /Applications/Spectacle.app"
cask "spotify" unless system "test -d /Applications/Spotify.app"
cask "dropbox" unless system "test -d /Applications/Dropbox.app"
cask "zoomus"
cask "intellij-idea-ce"
cask "docker"
cask "postman"
