#!/bin/bash

rm -f ~/.editorconfig ~/.bashrc ~/.inputrc ~/.vimrc
ln -s .dotfiles/editorconfig ~/.editorconfig
ln -s .dotfiles/bashrc ~/.bashrc
ln -s .dotfiles/inputrc ~/.inputrc
ln -s .dotfiles/vimrc ~/.vimrc
