#!/bin/bash

# Remove all previously created files
rm -f ~/.editorconfig \
        ~/.bash_profile \
        ~/.bashrc \
        ~/.bashprompt \
        ~/.inputrc \
        ~/.vimrc \
        ~/.screenrc \
        ~/.gitconfig \
        ~/.tmux.conf \

# Create symbolic links for all files of interest
ln -s .dotfiles/editorconfig ~/.editorconfig
ln -s .dotfiles/bash/bash_profile ~/.bash_profile
ln -s .dotfiles/bash/bashrc ~/.bashrc
ln -s .dotfiles/bash/bashprompt ~/.bashprompt
ln -s .dotfiles/inputrc ~/.inputrc
ln -s .dotfiles/vimrc ~/.vimrc
ln -s .dotfiles/screenrc ~/.screenrc
ln -s .dotfiles/gitconfig ~/.gitconfig
ln -s .dotfiles/tmux.conf ~/.tmux.conf
