set nocompatible
filetype off

" Set the runtime path to include Vundle and initialize
set rtp+=$PREFIX/vim/bundle/Vundle.vim
call vundle#begin('$XDG_CACHE_HOME/vim/bundle')
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'editorconfig/editorconfig-vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'Raimondi/delimitMate.git'
Plugin 'kien/ctrlp.vim'
Plugin 'elzr/vim-json'
Plugin 'unimpaired.vim'
Plugin 'derekwyatt/vim-scala'
Plugin 'aquach/vim-http-client'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'pangloss/vim-javascript'
Plugin 'Valloric/MatchTagAlways'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-commentary'
Plugin 'jparise/vim-graphql'
Plugin 'udalov/kotlin-vim'
call vundle#end()

set ruler
" relative line numbers based on current line
set relativenumber
" autolatically refresh file if changed on disk
set autoread

filetype plugin on
filetype indent on

" use Solarized Dark theme
syntax on
let g:solarized_termcolors=256
set background=dark
colorscheme solarized
let g:solarized_termtrans = 0
let g:solarized_contrast = "high"


" automatically close quotes, brackets, etc
let delimitMate_expand_cr = 0

" CtrlP
" directories to ignore
set wildignore+=*/target/**
" don't cache
let g:ctrlp_use_caching=0

" vim-http-client: use json filetype for better syntax highlighting
let g:http_client_json_ft="json"

" stop creating swp and ~ files
set nobackup
set noswapfile

" ignore case of `/` searches unless an upper case letter is used
set ignorecase
set smartcase

" remove ugly vertibal bars in split bar
set fillchars+=vert:\

" enable line numbers
set number

" highlight current line
set cursorline

" highlight searches
set hlsearch

" highlight dynamically as search pattern is typeds
set incsearch

" always show status line
set laststatus=2

" disable error bells
set noerrorbells

" don't reset cursor to start of line when moving around
set nostartofline

" set status bar theme
let g:lightline = { 'colorscheme': 'powerline' }

" dont' show mode - it's already available in status bar
set noshowmode
