# homebrew
eval $(brew shellenv)
#export HOMEBREW_CACHE="${XDG_CACHE_HOME}/Homebrew"
#export HOMEBREW_LOGS="${XDG_DATA_HOME}/logs/Homebrew"
export HOMEBREW_NO_EMOJI=1

GIT_PROMPT_ONLY_IN_REPO=1
BASH_GIT_PROMPT="${HOMEBREW_PREFIX}/opt/bash-git-prompt/share/gitprompt.sh"
if [ -f "$BASH_GIT_PROMPT" ]; then
  __GIT_PROMPT_DIR=$(dirname $BASH_GIT_PROMPT)
  . "$BASH_GIT_PROMPT"
fi

#export BASH_COMPLETION_COMPAT_DIR="${HOMEBREW_PREFIX}/etc/bash_completion.d"
[[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && . "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
